### ISSUE TITLE
How can I get the METADMG_RESULTS before running dmg-reads?

### ISSUE THREAD

**Issue by timeresistance1996** [genomewalker/dmg-reads#4]
Hallo,

    I use metaDMG resulted with .bdamage.gz, .res.gz, .rlens.gz and .stat files only. 

     How can I get the .csv.gz file required for dmg-reads? Could you give me some advice on metaDMG analyse options?

**Comment by genomewalker** [comment]
dReads is using the old metaDMG and still needs to be updated to use the new version. Check this [tutorial](https://github.com/genomewalker/ebame8/wiki/A-basic-primer-on-ancient-metagenomics) for tips. [Here](https://github.com/genomewalker/ebame8/blob/main/ebame8-aDNA-tutorial/install-metaDMG.sh) you have the instructions on how to install the former version and the [env](https://github.com/genomewalker/ebame8/blob/main/ebame8-aDNA-tutorial/metaDMG.yaml) file for the python part.

**Comment by timeresistance1996** [comment]
Thank you for that! I will have a try.
